#!/bin/zsh
#
# change default behaviors for the basics

. ~/.zsh/vars

# Host specific aliases
case $HOSTNAME in
	giGnote)
		alias outside="weatherget -s BEXX0008 -m"
	;;
	*)
		alias outside="weatherget -s BEXX0008 -m"
	;;
esac



alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

#PING / DNS

alias mv="mv -v --backup=existing"
alias mmv="noglob zmv -W"
alias rm="rm -v"
alias cp="cp -v"
#alias firefox="aoss firefox"
alias grep="grep --color=auto"
#alias irb="irb --simple-prompt"

#function call
alias ex=extract_archive

# abreviations

# basics
alias rm="rm -i -v"
alias c="clear"
#alias l="cd ."
alias l="ls++"
#alias ls='ls -hF -a --color=auto'
alias ls='ls++'
alias lss='/usr/bin/ls --color=auto'
alias ll='ls -ahl --color | more; echo "\e[0;30m[\e[0;32m Dirs:\e[1;36m `ls -l | egrep \"^drw\" | wc -l` \e[0;30m|\e[1;33m Files: \e[0;31m`ls -l | egrep -v \"^drw\" | grep -v total | wc -l` \e[0;30m]"'
#alias e="emacs -nw"
alias v="vim"
alias cdc="cd; clear"


# auto open images
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}="shotwell"
alias -s {mpg,mpeg,avi,ogm,wmv,m4v,mp4,mov}="vlc"
alias -s {mp3,ogg,wav,flac}="rhythmbox"
alias -s {html,php,com,net,org,gov}="firefox"

alias -s txt="vim"
alias -s pdf="xpdf"

alias pacupg='sudo pacman -Syu'        # Synchronize with repositories before upgrading packages that are out of date on the local system.
alias pacin='sudo pacman -S'           # Install specific package(s) from the repositories
alias pacins='sudo pacman -U'         # Install specific package not from the repositories but from a file 
alias pacre='sudo pacman -R'           # Remove the specified package(s), retaining its configuration(s) and required dependencies
alias pacrem='sudo pacman -Rns'        # Remove the specified package(s), its configuration(s) and unneeded dependencies
alias pacrep='pacman -Si'              # Display information about a given package in the repositories
alias pacreps='pacman -Ss'             # Search for package(s) in the repositories
alias pacloc='pacman -Qi'              # Display information about a given package in the local database
alias paclocs='pacman -Qs'             # Search for package(s) in the local database
alias paclocs='pacupd -Qu'             # Show packages to be upgraded

alias remd='sudo rm -r'
alias zetaf='sudo shutdown -h now'
alias reboot='sudo reboot'
alias svim='sudo vim'
alias snano='sudo nano'

alias redcolor="eval "`dircolors -b ~/.dircolors`""
alias vaconf='vim ~/.config/bspwm/bspwmrc'
