#!/bin/zsh

function precmd {

    local TERMWIDTH
    (( TERMWIDTH = ${COLUMNS} - 1 ))


    ###
    # Truncate the path if it's too long.
    
    PR_FILLBAR=""
    PR_PWDLEN=""
    
    local promptsize=${#${(%):---(%n@%m:%l)---()--}}
    local pwdsize=${#${(%):-%~}}
    
    if [[ "$promptsize + $pwdsize" -gt $TERMWIDTH ]]; then
	    ((PR_PWDLEN=$TERMWIDTH - $promptsize))
    else
	PR_FILLBAR="\${(l.(($TERMWIDTH - ($promptsize + $pwdsize)))..${PR_HBAR}.)}"
    fi
}


setopt extended_glob
preexec () {
    if [[ "$TERM" == "screen" ]]; then
		local CMD=${1[(wr)^(*=*|sudo|-*)]}
		if [[ "$CMD" == "zsh" ]]; then
			CMD=short_pwd
		fi
		#echo "\ek$CMD\e\\"
	elif [[ "$TERM" == "screen-256color" ]]; then
		local CMD=${1[(wr)^(*=*|sudo|-*)]}
		if [[ "$CMD" == "zsh" ]]; then
			CMD=short_pwd
		fi
		#echo -n "\ek$CMD\e\\"
	fi
}


setprompt () {
    ###
    # Need this so the prompt will work.

    setopt prompt_subst


    ###
    # See if we can use colors.

    autoload colors zsh/terminfo
    if [[ "$terminfo[colors]" -ge 8 ]]; then
	colors
    fi
    for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE BLACK; do
	eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
	eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
	(( count = $count + 1 ))
    done
    PR_NO_COLOUR="%{$terminfo[sgr0]%}"


    ###
    # See if we can use extended characters to look nicer.
    
    typeset -A altchar
    set -A altchar ${(s..)terminfo[acsc]}
    PR_SET_CHARSET="%{$terminfo[enacs]%}"
    PR_SHIFT_IN="%{$terminfo[smacs]%}"
    PR_SHIFT_OUT="%{$terminfo[rmacs]%}"
    PR_HBAR=${altchar[q]:--}
    PR_ULCORNER=${altchar[l]:--}
    PR_LLCORNER=${altchar[m]:--}
    PR_LRCORNER=${altchar[j]:--}
    PR_URCORNER=${altchar[k]:--}

    
    ###
    # Decide if we need to set titlebar text.
    
    case $TERM in
	xterm*)
	    PR_TITLEBAR=$'%{\e]0;%(!.-=*[ROOT]*=- | .)%n@%m:%~ | ${COLUMNS}x${LINES} | %y\a%}'
	    ;;
	screen)
	    PR_TITLEBAR=$'%{\e_screen \005 (\005t) | %(!.-=[ROOT]=- | .)%n@%m:%~ | ${COLUMNS}x${LINES} | %y\e\\%}'
	    ;;
	rxvt*)
	    PR_TITLEBAR=$'%{\e]0;%(!.-=*[ROOT]*=- | .)%n@%m:%~ | ${COLUMNS}x${LINES} | %y\a%}'
	    ;;
	*)
	    PR_TITLEBAR=''
	    ;;
    esac
    
    
    ###
    # Decide whether to set a screen title
    if [[ "$TERM" == "screen" ]]; then
	PR_STITLE=$'%{\ekzsh\e\\%}'
    else
	PR_STITLE=''
    fi
    
    
    ###
    # APM detection

PR_APM=''
    
    ###
    # Finally, the prompt.
#

SPROMPT="zsh: correct '%R' to '%r' ? ([Y]es/[N]o/[E]dit/[A]bort) "


if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    #alias ls='ls --color=auto'
    alias ls='ls++'
    #alias rm 'mv \!* ~/TRASH'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi


autoload -U colors && colors

## ORIGINAL

#PROMPT='$PR_SET_CHARSET$PR_STITLE${(e)PR_TITLEBAR}\
#$PR_CYAN$PR_SHIFT_IN$PR_ULCORNER$PR_BLUE$PR_HBAR$PR_SHIFT_OUT(\
#$PR_GREEN%(!.%SROOT%s.%n)@%m:%l$PR_BLUE)\
#$PR_SHIFT_IN$PR_HBAR$PR_CYAN$PR_HBAR${(e)PR_FILLBAR}$PR_BLUE$PR_HBAR$PR_SHIFT_OUT(\
#$PR_MAGENTA%$PR_PWDLEN<...<%~%<<\
#$PR_BLUE)$PR_SHIFT_IN$PR_HBAR$PR_CYAN$PR_URCORNER$PR_SHIFT_OUT\

#$PR_CYAN$PR_SHIFT_IN$PR_LLCORNER$PR_BLUE$PR_HBAR$PR_SHIFT_OUT(\
#%(?..$PR_LIGHT_RED%?$PR_BLUE:)\
#$PR_YELLOW\
#$PR_CYAN$PR_SHIFT_IN\
#%{$reset_color%}$PR_YELLOW%T$PR_BLUE:%(!.$PR_LIGHT_RED.$PR_CYAN)%{$reset_color%}%#$PR_BLUE)$PR_HBAR$PR_CYAN$PR_HBAR$PR_SHIFT_OUT%{$reset_color%} '

#RPROMPT='$PR_SHIFT_IN$PR_CYAN$PR_HBAR$PR_BLUE$PR_HBAR($PR_YELLOW$PR_SHIFT_OUT%D{%a,%b%d}$PR_SHIFT_IN$PR_BLUE)$PR_HBAR\
#$PR_BLUE$PR_SHIFT_IN$PR_CYAN$PR_LRCORNER$PR_SHIFT_OUT%{$reset_color%}'

## END OF ORIGINAL

## CUSTOM

#PROMPT='$PR_SET_CHARSET$PR_STITLE${(e)PR_TITLEBAR}\
#$PR_BLUE$PR_SHIFT_IN$PR_ULCORNER$PR_BLUE$PR_HBAR$PR_SHIFT_OUT \
#$PR_YELLOW%(!.%SROOT%s.%n)$PR_BLUE@$PR_GREEN%m $PR_BLUE$PR_SHIFT_IN$PR_HBAR$PR_SHIFT_OUT $PR_RED%T $PR_BLUE$PR_SHIFT_IN$PR_HBAR$PR_SHIFT_OUT $PR_LIGHT_CYAN%l $PR_BLUE$PR_SHIFT_IN$PR_HBAR$PR_SHIFT_OUT $PR_MAGENTA%$PR_PWDLEN<...<%~%<< $PR_BLUE$PR_SHIFT_IN$PR_HBAR$PR_SHIFT_OUT\

#$PR_SHIFT_IN$PR_LLCORNER$PR_BLUE$PR_HBAR$PR_SHIFT_OUT \
#%(?..$PR_LIGHT_RED%?$PR_BLUE:)\
#$PR_YELLOW\
#$PR_SHIFT_IN\
#%{$reset_color%}%{$reset_color%}%#$PR_BLUE $PR_HBAR$PR_SHIFT_OUT%{$reset_color%} '

#RPROMPT='$PR_SHIFT_IN$PR_CYAN$PR_HBAR$PR_BLUE$PR_HBAR($PR_YELLOW$PR_SHIFT_OUT%D{%a,%b%d}$PR_SHIFT_IN$PR_BLUE)$PR_HBAR\
#$PR_BLUE$PR_SHIFT_IN$PR_CYAN$PR_LRCORNER$PR_SHIFT_OUT%{$reset_color%}'


## END OF CUSTOM

## CUSTOM 2

#PROMPT='$PR_SET_CHARSET$PR_STITLE${(e)PR_TITLEBAR}\
#$PR_LIGHT_BLACK$PR_SHIFT_IN$PR_ULCORNER$PR_LIGHT_BLACK$PR_HBAR$PR_SHIFT_OUT \
#$PR_LIGHT_BLUE%$PR_PWDLEN<...<%~%<<\

#$PR_LIGHT_BLACK$PR_SHIFT_IN$PR_LLCORNER$PR_LIGHT_BLACK$PR_HBAR$PR_SHIFT_OUT \
#%(?..$PR_LIGHT_RED%?$PR_LIGHT_BLACK:)\
#$PR_LIGHT_BLACK\
#%{$reset_color%}%{$reset_color%}%#%{$reset_color%} '

## END OF CUSTOM 2

## CUSTOM 3

#PROMPT='$PR_SET_CHARSET$PR_STITLE${(e)PR_TITLEBAR}\
#$PR_LIGHT_GREEN%(!.%{$PR_LIGHT_RED%}root%s.%n)%{$reset_color%}@$PR_LIGHT_CYAN%m\
#%{$reset_color%}:$PR_YELLOW%$PR_PWDLEN<...<%~%<<\
#$PR_RED »\
#%{$reset_color%} '

## END OF CUSTOM 3

## CUSTOM 4
###########NAZADNJE

#PROMPT='$PR_SET_CHARSET$PR_STITLE${(e)PR_TITLEBAR}\
#$PR_CYAN%(!.%{$PR_CYAN%}root%s.%n)@%{$reset_color%}[%m]\
#:%$PR_PWDLEN<...<%~%<< %%\
#%{$reset_color%} '

## END OF CUSTOM 4

#PROMPT='$PR_SET_CHARSET$PR_STITLE${(e)PR_TITLEBAR}\
#$PR_CYAN$PR_SHIFT_IN$PR_ULCORNER$PR_BLUE$PR_HBAR$PR_SHIFT_OUT(\
#$PR_YELLOW%(!.%SROOT%s.%n)$PR_BLUE)\
#$PR_SHIFT_IN$PR_HBAR$PR_CYAN$PR_HBAR$PR_BLUE$PR_HBAR$PR_SHIFT_OUT(\
#$PR_YELLOW%$PR_PWDLEN<...<%~%<<\
#$PR_BLUE)\

#$PR_CYAN$PR_SHIFT_IN$PR_LLCORNER$PR_BLUE$PR_HBAR$PR_SHIFT_OUT(\
#%(?..$PR_LIGHT_RED%?$PR_BLUE:)\
#$PR_YELLOW\
#$PR_CYAN$PR_SHIFT_IN\
#%{$reset_color%}$PR_YELLOW$PR_BLUE%(!.$PR_LIGHT_RED.$PR_CYAN)$PR_YELLOW%#$PR_BLUE)$PR_HBAR$PR_CYAN$PR_HBAR$PR_SHIFT_OUT%{$reset_color%} '


##CUSTOM 6

PROMPT='$PR_SET_CHARSET$PR_STITLE$PR_BLUE${(e)PR_TITLEBAR}\
[%$PR_PWDLEN<...<%~%<<]$PR_GREEN%(!.%S$PR_LIGHT_RED>.$PR_GREEN>)\
%{$reset_color%} '

#RPROMPT='%$PR_PWDLEN<...<%~%<< '
}

setprompt
