#! /bin/sh

bspc config border_width        3
bspc config window_gap         12
bspc config top_padding        25
bspc config bottom_padding     16
bspc config right_padding      16
bspc config left_padding       16

bspc config normal_border_color         "#9a9a9a"
bspc config focused_border_color        "#ffffff"
bspc config active_border_color         "#ffffff"
bspc config presel_border_color         "#ff5879"

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d a b c d e f g 

bspc rule -a Gimp desktop=^7
bspc rule -a Firefox desktop=^2 follow=on
bspc rule -a tor-browser-en desktop=^2 follow=on
bspc rule -a Transmission-gtk desktop=^5 follow=on
bspc rule -a mplayer2 floating=on
bspc rule -a Screenkey manage=off

## autostart
/home/nu/.bspwm_auto &
