#!/bin/sh
source $HOME/.config/bspwm/scripts/config.sh
# Figure out current screen size
SCREENWIDTH=$(xrandr -q | grep Screen | awk '{print $8}')
SCREENHEIGHT=$(xrandr -q | grep Screen | awk '{print $10}' | sed s/,//)

# How close to the screen edges do we begin/end?
EDGEWIDTH=0
DMENUWIDTH=$(($SCREENWIDTH - $(($EDGEWIDTH + $EDGEWIDTH))))

# dmenu X/Y coordinates
#XPOS=$EDGEWIDTH
#YPOS=$(($(($SCREENHEIGHT / 2)) - 15))
XPOS=0
YPOS=0

FGSELECT="#dddddd"
BGSELECT="#afd700"
#FONT="-gohu-gohufont-medium-r-normal--11-80-100-100-c-60-iso8859-1"
#FONT="-artwiz-snap-normal-r-normal--10-100-75-75-p-90-iso8859-1"

dmenu_run -h 13 -w $DMENUWIDTH -x $XPOS -y $YPOS -fn ${FONT} -sb $BGSELECT -sf $FG -nb $BG -nf $FGSELECT -p ">" -class dmenu
